# -*- coding: utf-8 -*-
"""CP01_JoaoCarmo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/108E20DI1N8-3Y5VSPJVKtHleocrBtDPp
"""

# Setup - nao modifique
!pip install -q tiktoken sentence-transformers huggingface_hub matplotlib numpy scikit-learn

import tiktoken
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.decomposition import PCA
from sentence_transformers import SentenceTransformer
from huggingface_hub import InferenceClient
from google.colab import userdata
import time

try:
    HF_TOKEN = userdata.get("HF_TOKEN")
    print("Token HF carregado")
except:
    HF_TOKEN = None
    print("Configure HF_TOKEN em Colab Secrets")

encoder = tiktoken.get_encoding("cl100k_base")
modelo_emb = SentenceTransformer("all-MiniLM-L6-v2")
print("Setup completo!")

"""DESAFIO 1"""

# Importa o tokenizador (exemplo com tiktoken - usado em LLMs como GPT)
import tiktoken

# Define qual encoding será usado (depende do modelo)
encoder = tiktoken.get_encoding("cl100k_base")


# =========================================================
# FUNÇÃO: analisar_tokens
# Objetivo: analisar um texto e extrair métricas de tokens
# =========================================================
def analisar_tokens(texto):

    # Converte o texto em tokens (unidades que o modelo entende)
    tokens = encoder.encode(texto)

    return {
        # Retorna apenas os primeiros 60 caracteres (resumo do texto)
        "texto": texto[:60],

        # Quantidade total de caracteres no texto original
        "num_caracteres": len(texto),

        # Quantidade de tokens gerados pelo tokenizador
        "num_tokens": len(tokens),

        # Relação caracteres por token (ajuda a entender eficiência)
        # Quanto maior, melhor (menos tokens para representar o texto)
        "ratio": len(texto) / len(tokens) if len(tokens) > 0 else 0,

        # Decodifica os primeiros 10 tokens para visualização
        # Útil para entender como o texto foi quebrado
        "tokens_decodificados": [encoder.decode([t]) for t in tokens[:10]]
    }


# =========================================================
# DADOS DE TESTE
# 3 pares com mesmo significado em PT-BR e inglês
# =========================================================
pares = [
    {
        "pt": "Inteligência Artificial está transformando o mercado de tecnologia e criando novas oportunidades.",
        "en": "Artificial Intelligence is transforming the technology market and creating new opportunities."
    },
    {
        "pt": "Modelos de linguagem são usados para gerar texto, responder perguntas e automatizar tarefas.",
        "en": "Language models are used to generate text, answer questions, and automate tasks."
    },
    {
        "pt": "O processamento de dados em larga escala exige infraestrutura robusta e otimizada.",
        "en": "Large-scale data processing requires robust and optimized infrastructure."
    }
]


# =========================================================
# COMPARAÇÃO ENTRE PT-BR E INGLÊS
# =========================================================
print("COMPARACAO PT-BR vs INGLES")
print("=" * 60)

# Percorre cada par de textos
for i, par in enumerate(pares, 1):

    # Analisa o texto em português
    a_pt = analisar_tokens(par["pt"])

    # Analisa o texto em inglês
    a_en = analisar_tokens(par["en"])

    # Calcula a diferença de tokens entre PT e EN
    diff = a_pt["num_tokens"] - a_en["num_tokens"]

    # Exibe resultados
    print(f"\nPar {i}:")
    print(f"PT-BR: {a_pt['num_tokens']} tokens | {a_pt['num_caracteres']} chars")
    print(f"EN   : {a_en['num_tokens']} tokens | {a_en['num_caracteres']} chars")

    # Mostra diferença (positivo = PT maior, negativo = EN maior)
    print(f"Diferenca de tokens: {diff:+d}")

    # Mostra eficiência (chars por token)
    print(f"Ratio PT: {a_pt['ratio']:.2f}")
    print(f"Ratio EN: {a_en['ratio']:.2f}")

    # Mostra como os tokens foram quebrados
    print(f"Tokens PT (amostra): {a_pt['tokens_decodificados']}")
    print(f"Tokens EN (amostra): {a_en['tokens_decodificados']}")

    print("-" * 60)

"""DESAFIO 2"""

# Biblioteca para embeddings e similaridade
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity


# =========================
# MODELO DE EMBEDDING
# =========================
# Modelo leve e eficiente para similaridade semântica
modelo_emb = SentenceTransformer('all-MiniLM-L6-v2')


# =========================
# CLASSE PRINCIPAL
# =========================
class MotorSimilaridade:

    def __init__(self, textos, labels):
        """
        Inicializa o motor com textos e seus rótulos.
        """
        self.textos = textos
        self.labels = labels

        # Gera embeddings vetoriais para todos os textos
        # Cada texto vira um vetor numérico
        self.embeddings = modelo_emb.encode(textos)


    def matriz_similaridade(self):
        """
        Calcula matriz de similaridade entre todos os textos.
        """
        return cosine_similarity(self.embeddings)


    def mais_similar(self, query):
        """
        Encontra o texto mais similar a uma query.
        """

        # Gera embedding da query
        emb_q = modelo_emb.encode([query])

        # Calcula similaridade entre query e todos os textos
        scores = cosine_similarity(emb_q, self.embeddings)[0]

        # Encontra índice do maior score
        idx = scores.argmax()

        # Retorna label, score e texto mais similar
        return self.labels[idx], float(scores[idx]), self.textos[idx]


    def exibir_matriz(self):
        """
        Exibe matriz de similaridade formatada.
        """
        mat = self.matriz_similaridade()

        # Cabeçalho com labels
        header = " " * 10 + " ".join(f"{l:>10}" for l in self.labels)
        print(header)

        # Linhas da matriz
        for i, l in enumerate(self.labels):
            print(f"{l:>10} " + " ".join(f"{mat[i][j]:>10.3f}" for j in range(len(self.labels))))


# =========================
# DADOS (SEU DOMÍNIO - IA/TECH)
# =========================
textos = [
    "Inteligência artificial está revolucionando o mercado de tecnologia.",  # A
    "A IA está transformando a indústria de tecnologia rapidamente.",        # B (similar a A)
    "Modelos de linguagem são usados para gerar textos automaticamente.",    # C (diferente de A/B)
    "Análise de dados ajuda empresas a tomar decisões melhores.",            # D
    "A análise de dados é essencial para decisões estratégicas.",            # E (similar a D)
    "Cachorros gostam de brincar no parque durante o dia."                   # F (totalmente diferente)
]

labels = ["A", "B", "C", "D", "E", "F"]


# =========================
# EXECUÇÃO
# =========================
motor = MotorSimilaridade(textos, labels)

print("MATRIZ DE SIMILARIDADE")
motor.exibir_matriz()


# =========================
# TESTE DE BUSCA
# =========================
query = "Como a inteligência artificial impacta empresas de tecnologia?"

if query:
    l, s, t = motor.mais_similar(query)

    print("\n🔍 Busca Semântica")
    print(f"Query: {query}")
    print(f"Mais similar: [{l}] (score={s:.3f})")
    print(f"Texto: {t}")

"""DESAFIO 3"""

# =========================
# IMPORTS
# =========================
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA


# =========================
# FUNÇÃO: plotar mapa 2D
# =========================
def plotar_mapa(motor, cores_por_label):
    """
    Projeta embeddings em 2D usando PCA e plota um mapa semântico.
    """

    # Reduz dimensionalidade (ex: 384 → 2 dimensões)
    pca = PCA(n_components=2)

    # Aplica PCA nos embeddings
    coords = pca.fit_transform(motor.embeddings)

    # Variância explicada por cada componente
    var1 = pca.explained_variance_ratio_[0]
    var2 = pca.explained_variance_ratio_[1]

    # Cria figura
    fig, ax = plt.subplots(figsize=(11, 7))

    # Percorre cada ponto (texto)
    for i, (x, y) in enumerate(coords):

        # Define cor baseada no label
        cor = cores_por_label.get(motor.labels[i], "#999")

        # Plota ponto no gráfico
        ax.scatter(
            x, y,
            c=cor,
            s=200,
            edgecolors="#333",
            linewidths=0.5,
            zorder=5
        )

        # Adiciona label próximo ao ponto
        ax.annotate(
            motor.labels[i],
            (x, y),
            textcoords="offset points",
            xytext=(0, 10),
            ha='center',
            fontsize=9,
            color=cor
        )

    # Títulos e labels
    ax.set_title("Mapa Semântico - Embeddings 2D", fontsize=14, fontweight="bold")
    ax.set_xlabel(f"PC1 ({var1:.1%} variância)")
    ax.set_ylabel(f"PC2 ({var2:.1%} variância)")

    # Grid para melhor leitura
    ax.grid(True, alpha=0.2)

    # Ajuste layout
    plt.tight_layout()
    plt.show()


# =========================
# CORES DOS LABELS
# =========================
cores = {
    "A": "#ED145B",  # IA
    "B": "#ED145B",  # IA similar
    "C": "#3D9CCC",  # NLP
    "D": "#29AF8C",  # dados
    "E": "#29AF8C",  # dados similar
    "F": "#7C60C6"   # fora do domínio
}


# =========================
# EXECUÇÃO
# =========================
plotar_mapa(motor, cores)

"""DESAFIO 4"""

# DESAFIO 4: Complete o laboratório de temperatura
# Teste 3 temperaturas diferentes e gere um gráfico de consistência

MODELO = "mistral/Mistral-7B-Instruct-v0.3"
client = InferenceClient(token=HF_TOKEN)

# -------------------------------------------
# Função que chama o modelo com temperatura
# -------------------------------------------
def chamar_llm(prompt, temperature=0.7, max_tokens=200):
    """
    Envia um prompt ao LLM com uma temperatura específica.
    Retorna apenas o texto da resposta.
    """
    try:
        resp = client.chat.completions.create(
            model=MODELO,
            messages=[{"role": "user", "content": prompt}],
            temperature=temperature,
            max_tokens=max_tokens
        )
        return resp.choices[0].message.content.strip()

    except Exception as e:
        return f"Erro: {e}"


# ------------------------------------------------------------
# Função para testar várias temperaturas repetidas vezes
# ------------------------------------------------------------
def lab_temperatura(prompt, temps=(0.1, 0.7, 1.5), reps=2):
    """
    Executa o mesmo prompt várias vezes com temperaturas diferentes.
    Calcula:
        - respostas obtidas
        - quantidade de respostas únicas
        - consistência (%)
    """
    resultados = {}

    for temp in temps:
        respostas = []

        # Fazer reps chamadas por temperatura
        for _ in range(reps):
            r = chamar_llm(prompt, temperature=temp)
            respostas.append(r)
            time.sleep(2)  # evita rate-limit

        # respostas únicas
        unicas = len(set([r[:50] for r in respostas]))

        # consistência = quanto as respostas são semelhantes (%)
        consistencia = (1 - (unicas - 1) / max(reps - 1, 1)) * 100

        resultados[temp] = {
            "respostas": respostas,
            "consistencia": consistencia
        }

    return resultados


# -------------------------------------------
# Defina aqui o prompt para o teste
# -------------------------------------------
MEU_PROMPT = "Explique o que é inteligência artificial em 2 frases."

# -------------------------------------------
# Executar o laboratório
# -------------------------------------------
if MEU_PROMPT:
    res = lab_temperatura(MEU_PROMPT)

    for t, d in res.items():
        print(f"\nTemperatura {t} - Consistência: {d['consistencia']:.0f}%")
        for i, r in enumerate(d["respostas"], 1):
            print(f"  Resposta {i}: {r[:100]}...")

# -------------------------------------------
# Gerar gráfico
# -------------------------------------------
temps = list(res.keys())
consist = [res[t]["consistencia"] for t in temps]

plt.figure(figsize=(8, 5))
plt.bar([str(t) for t in temps], consist)
plt.title("Consistência por Temperatura")
plt.xlabel("Temperatura")
plt.ylabel("Consistência (%)")
plt.ylim(0, 100)
plt.tight_layout()
plt.show()

"""DESAFIO 5"""

# DESAFIO 5: Complete a função de demonstração de pipeline
from transformers import pipeline
import warnings
warnings.filterwarnings("ignore")

def demonstrar_pipeline(nome, textos, subarea):
    """
    Executa um pipeline de IA (ex.: sentiment-analysis, summarization, etc.)
    e demonstra como cada subárea resolve um tipo diferente de problema.
    """
    print(f"\nPipeline: {nome} | Subárea: {subarea}")
    print("-" * 60)

    # Criar o pipeline desejado
    pipe = pipeline(nome)

    # Executar o pipeline para cada texto
    for texto in textos:
        if not texto:
            continue

        resultado = pipe(texto)

        print(f"\n📌 Input: \"{texto[:60]}...\"")
        print(f"➡️  Output: {resultado}")


# -----------------------------------------------
# Pipeline 1: ANÁLISE DE SENTIMENTO
# -----------------------------------------------
demonstrar_pipeline(
    "sentiment-analysis",
    [
        "Estou muito satisfeito com o atendimento!",
        "O produto chegou quebrado, fiquei muito decepcionado.",
        "Nada demais, achei apenas razoável."
    ],
    subarea="NLP – Classificação de Sentimento"
)

print("\n" + "=" * 60)

# -----------------------------------------------
# Pipeline 2: GERAÇÃO DE TEXTO
# -----------------------------------------------
demonstrar_pipeline(
    "text-generation",
    [
        "Escreva uma frase motivacional sobre tecnologia.",
        "Conte uma pequena história sobre um programador iniciante.",
    ],
    subarea="NLP – Geração de Texto"
)